# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def sum(max)
  new_term = 0
  sequence = [1, 2]
  while new_term < max
    new_term = sequence[-1] + sequence[-2]
    sequence << new_term
  end
  sequence.pop
  p sequence
  p sequence.select(&:even?).sum
end

sum(4000000)